### ISSUE TITLE
File to import not found or unreadable: envb_mixins.

### ISSUE THREAD

**Issue by ramanbuttar** [joedynamite/envb-rails#3]
Added gem to new Rails project

`application.css` manifest file looks like:

```
 *
 *= require_tree .
 *= require envb
 *= require_self
 */
```

Rails server starts just fine. Hitting http://localhost:3000 throws the above error.

**Comment by joedynamite** [comment]
@ramanbuttar wow, sorry I didn’t even see this issue get posted. I assume you’re still getting this error. Could you let me know which version of Rails you were using and I’ll see if I can figure out the problem?

**Comment by ramanbuttar** [comment]
@joedynamite Still getting the error. Using Rails 4.2 and Ruby 2.3.1

**Comment by ramanbuttar** [comment]
Updating https://github.com/joedynamite/envb-rails/blob/ea0e62e6651d6740b74224194ebbf65608bb68d7/app/assets/stylesheets/envb.css.scss.erb#L3 to read
`@import 'envb_mixins.css.scss';` worked for me.
